RecodeCHC <- function(col) {
  # Recodes the CHC acronyms to long CHC labels
  #
  # Args:
  #   x: a column from a data frame that includes CHC acronyms.
  #
  # Returns:
  #   The long CHC labels.
  recode(col,
         "g" = "General Ability",
         "Gf/Gv" = "Fluid Reasoning and Visual Processing",
         "Gc" = "Comprehension-Knowledge",
         "Gc:CM" = "Communication Ability",
         "Gc:K0" = "General Verbal Information",
         "Gc:VL" = "Lexical Knowledge",
         "Gc:LD" = "Language Development",
         "Gc:LS" = "Listening Ability",
         "Gc:MY" = "Grammatical Sensitivity",
         "Gf" = "Fluid Reasoning",
         "Gf:I" = "Induction",
         "Gf:RG" = "General Sequential Reasoning",
         "Gf:RQ" = "Quantitative Reasoning",
         "Gf:RE" = "Reasoning Speed",
         "Gf:RP" = "Piagetian Reasoning",
         "Glr" = "Long-Term Storage and Retrieval",
         "Gl" = "Learning Efficiency",
         "Gr" = "Retrieval Fluency",
         "Gr:FF" = "Figural Fluency",
         "Gr:FE" = "Expressional Fluency",
         "Gr:FA" = "Associational Fluency",
         "Gr:SP" = "Alternative Solution Fluency",
         "Gr:FO" = "Creativity",
         "Gr:LA" = "Speed of Lexical Access",
         "Gr:FX" = "Figural Flexibility",
         "Gr:FI" = "Ideational Fluency",
         "Gr:FW" = "Word Fluency",
         "Gr:NA" = "Naming Facility",
         "Gl:M6" = "Free-recall Memory",
         "Gl:MA" = "Associative Memory",
         "Gl:MM" = "Meaningful Memory",
         "Gwm" = "Short-Term Working Memory",
         "Gwm:Wa" = "Auditory Short-Term Storage",
         "Gwm:Wv" = "Visual-Spatial Short-Term Storage",
         "Gwm:AC" = "Attentional Control",
         "Gwm:Wc" = "Working Memory Capacity",
         "Gv" = "Visual-Spatial Processing",
         "Gv:Vz" = "Visualization",
         "Gv:SR" = "Speeded Rotation",
         "Gv:IM" = "Imagery",
         "Gv:CS" = "Closure Speed",
         "Gv:CF" = "Flexibility of Closure",
         "Gv:MV" = "Visual Memory",
         "Gv:SS" = "Spatial Scanning",
         "Gv:PI" = "Serial Perceptual Integration",
         "Gv:LE" = "Length Estimation",
         "Gv:IL" = "Perceptual Illuisions",
         "Gv:PN" = "Perceptual Alterations",
         "Gv:P" = "Perceptual Speed",
         "Ga" = "Auditory Processing",
         "Ga:PC" = "Phonetic Coding",
         "Ga:US" = "Speech Sound Discrimination",
         "Ga:UR" = "Resistance ot Auditory Stimulus Distortion",
         "Ga:U8" = "Maintaining and Judging Rhythm",
         "Ga:UM" = "Memory for Sound Patterns",
         "Ga:U1U9" = "Musical Discrimination and Judgement",
         "Ga:UP" = "Absolute Pitch",
         "Ga:UL" = "Sound Localisation",
         "Gkn" = "Domain Specific Knowledge",
         "Gkn:K1" = "General Science Information",
         "Gkn:K2" = "Knowledge of Culture",
         "Gkn:MK" = "Mechanical Knowledge",
         "Gkn:KL" = "Foreign Language Proficiency",
         "Gkn:KF" = "Knowledge of Signing",
         "Gkn:LP" = "Skill in Lip Reading",
         "Grw" = "Reading and Writing",
         "Grw:RC" = "Reading Comprehension",
         "Grw:RD" = "Reading Decoding",
         "Grw:RS" = "Reading Speed",
         "Grw:WA" = "Writing Ability",
         "Grw:SG" = "Spelling Ability",
         "Grw:WS" = "Writing Speed",
         "Grw:EU" = "English Usage",
         "Gq" = "Quantiative Knowledge",
         "Gq:KM" = "Mathematical Knowledge",
         "Gq:A3" = "Mathematical Achievement",
         "Gs" = "Processing Speed",
         "Gs:P" = "Perceptual Speed",
         "Gs:Ps" = "Perceptual Speed Search",
         "Gs:Pc" = "Perceptual Speed Compare",
         "Gs:N" = "Number Facility",
         "Gs:RS" = "Reading Speed",
         "Gs:WS" = "Writing Speed",
         "ACH" = "Achievement"
  )
}
